<?php

namespace App\StructuralCalculation\Eurocode\Cover;

enum CoverCalculationRejectionReason: string
{
    case NO_EXPOSURE_CLASS = 'NO_EXPOSURE_CLASS';
    case INVALID_REINFORCEMENT_DIAMETER = 'INVALID_REINFORCEMENT_DIAMETER';
    case INVALID_DESIGN_WORKING_LIFE = 'INVALID_DESIGN_WORKING_LIFE';
    case UNSUPPORTED_EXPOSURE_CLASS = 'UNSUPPORTED_EXPOSURE_CLASS';
    case STRUCTURAL_CLASS_RULE_NOT_SUPPORTED = 'STRUCTURAL_CLASS_RULE_NOT_SUPPORTED';
    case INVALID_MANUAL_NOMINAL_COVER = 'INVALID_MANUAL_NOMINAL_COVER';
    case UNSUPPORTED_CONFIGURATION = 'UNSUPPORTED_CONFIGURATION';
}
