<?php

namespace App\StructuralCalculation\Slabs;

enum SlabStripLinearLoadsRejectionReason: string
{
    case INVALID_EFFECTIVE_SPAN = 'INVALID_EFFECTIVE_SPAN';
    case INVALID_CALCULATION_STRIP_WIDTH = 'INVALID_CALCULATION_STRIP_WIDTH';
    case INVALID_ULTIMATE_SURFACE_LOAD = 'INVALID_ULTIMATE_SURFACE_LOAD';
    case INVALID_CHARACTERISTIC_SURFACE_LOAD = 'INVALID_CHARACTERISTIC_SURFACE_LOAD';
    case INVALID_FREQUENT_SURFACE_LOAD = 'INVALID_FREQUENT_SURFACE_LOAD';
    case INVALID_QUASI_PERMANENT_SURFACE_LOAD = 'INVALID_QUASI_PERMANENT_SURFACE_LOAD';
}
