<?php

namespace App\StructuralCalculation\Slabs;

enum SlabCharacteristicActionsRejectionReason: string
{
    case INVALID_THICKNESS = 'INVALID_THICKNESS';
    case INVALID_REINFORCED_CONCRETE_UNIT_WEIGHT = 'INVALID_REINFORCED_CONCRETE_UNIT_WEIGHT';
    case INVALID_FINISHES = 'INVALID_FINISHES';
    case INVALID_PARTITIONS = 'INVALID_PARTITIONS';
    case INVALID_OTHER_PERMANENT = 'INVALID_OTHER_PERMANENT';
    case INVALID_IMPOSED_LOAD = 'INVALID_IMPOSED_LOAD';
}
