<?php

namespace App\StructuralCalculation\Slabs;

enum SlabSurfaceLoadsRejectionReason: string
{
    case MISSING_FINISHES = 'MISSING_FINISHES';
    case INVALID_FINISHES = 'INVALID_FINISHES';
    case MISSING_PARTITIONS = 'MISSING_PARTITIONS';
    case INVALID_PARTITIONS = 'INVALID_PARTITIONS';
    case MISSING_OTHER_PERMANENT = 'MISSING_OTHER_PERMANENT';
    case INVALID_OTHER_PERMANENT = 'INVALID_OTHER_PERMANENT';
    case MISSING_IMPOSED_LOAD = 'MISSING_IMPOSED_LOAD';
    case INVALID_IMPOSED_LOAD = 'INVALID_IMPOSED_LOAD';
}
