<?php

namespace App\StructuralCalculation\Slabs;

enum SlabConfigurationRejectionReason: string
{
    case INVALID_CONFIGURATION_VALUE = 'INVALID_CONFIGURATION_VALUE';
    case UNSUPPORTED_ELEMENT_TYPE = 'UNSUPPORTED_ELEMENT_TYPE';
    case UNSUPPORTED_SLAB_TYPE = 'UNSUPPORTED_SLAB_TYPE';
    case UNSUPPORTED_SPANNING_SYSTEM = 'UNSUPPORTED_SPANNING_SYSTEM';
    case UNSUPPORTED_STRUCTURAL_SYSTEM = 'UNSUPPORTED_STRUCTURAL_SYSTEM';
    case UNSUPPORTED_LOAD_MODEL = 'UNSUPPORTED_LOAD_MODEL';
    case UNSUPPORTED_MATERIAL_TYPE = 'UNSUPPORTED_MATERIAL_TYPE';
    case UNSUPPORTED_DESIGN_CODE_PROFILE = 'UNSUPPORTED_DESIGN_CODE_PROFILE';
    case UNSUPPORTED_DESIGN_SITUATION = 'UNSUPPORTED_DESIGN_SITUATION';
}
