<?php

namespace App\StructuralCalculation\Eurocode\Combinations;

enum ActionCombinationRejectionReason: string
{
    case INVALID_TOTAL_PERMANENT_LOAD = 'INVALID_TOTAL_PERMANENT_LOAD';
    case INVALID_VARIABLE_CHARACTERISTIC_LOAD = 'INVALID_VARIABLE_CHARACTERISTIC_LOAD';
    case INVALID_UNFAVOURABLE_PERMANENT_PARTIAL_FACTOR = 'INVALID_UNFAVOURABLE_PERMANENT_PARTIAL_FACTOR';
    case INVALID_VARIABLE_PARTIAL_FACTOR = 'INVALID_VARIABLE_PARTIAL_FACTOR';
    case MISSING_VARIABLE_ACTION_FACTORS = 'MISSING_VARIABLE_ACTION_FACTORS';
    case INVALID_FREQUENT_VARIABLE_FACTOR = 'INVALID_FREQUENT_VARIABLE_FACTOR';
    case INVALID_QUASI_PERMANENT_VARIABLE_FACTOR = 'INVALID_QUASI_PERMANENT_VARIABLE_FACTOR';
}
