<?php

namespace App\StructuralCalculation\Materials\Exposure;

enum DegradationMechanism: string
{
    case REINFORCEMENT_CORROSION_BY_CARBONATION = 'REINFORCEMENT_CORROSION_BY_CARBONATION';
    case REINFORCEMENT_CORROSION_BY_CHLORIDES = 'REINFORCEMENT_CORROSION_BY_CHLORIDES';
    case FREEZE_THAW_DAMAGE = 'FREEZE_THAW_DAMAGE';
    case CHEMICAL_CONCRETE_ATTACK = 'CHEMICAL_CONCRETE_ATTACK';
}
