<?php

namespace App\StructuralCalculation\Beams;

enum BeamShearReinforcementDesignRejectionReason: string
{
    case INVALID_DESIGN_SHEAR_FORCE = 'INVALID_DESIGN_SHEAR_FORCE';
    case INVALID_CONCRETE_SHEAR_RESISTANCE = 'INVALID_CONCRETE_SHEAR_RESISTANCE';
    case INVALID_WEB_WIDTH = 'INVALID_WEB_WIDTH';
    case INVALID_LEVER_ARM = 'INVALID_LEVER_ARM';
    case INVALID_CONCRETE_STRENGTH = 'INVALID_CONCRETE_STRENGTH';
    case INVALID_STEEL_CHARACTERISTIC_STRENGTH = 'INVALID_STEEL_CHARACTERISTIC_STRENGTH';
    case INVALID_STIRRUP_STEEL_DESIGN_STRENGTH = 'INVALID_STIRRUP_STEEL_DESIGN_STRENGTH';
    case INVALID_MINIMUM_COT_THETA = 'INVALID_MINIMUM_COT_THETA';
    case INVALID_MAXIMUM_COT_THETA = 'INVALID_MAXIMUM_COT_THETA';
    case INVALID_MINIMUM_SHEAR_REINFORCEMENT_COEFFICIENT = 'INVALID_MINIMUM_SHEAR_REINFORCEMENT_COEFFICIENT';
    case INVALID_DESIGN_COT_THETA = 'INVALID_DESIGN_COT_THETA';
    case DESIGN_COT_THETA_OUTSIDE_PROFILE_RANGE = 'DESIGN_COT_THETA_OUTSIDE_PROFILE_RANGE';
}
