<?php

namespace App\StructuralCalculation\Beams;

enum BeamDeflectionVerificationRejectionReason: string
{
    case CALCULATION_METHOD_NOT_SUPPORTED = 'CALCULATION_METHOD_NOT_SUPPORTED';
    case INSUFFICIENT_LONGITUDINAL_REINFORCEMENT = 'INSUFFICIENT_LONGITUDINAL_REINFORCEMENT';
    case INVALID_EFFECTIVE_SPAN = 'INVALID_EFFECTIVE_SPAN';
    case INVALID_EFFECTIVE_DEPTH = 'INVALID_EFFECTIVE_DEPTH';
    case INVALID_TENSION_WIDTH = 'INVALID_TENSION_WIDTH';
    case INVALID_CONCRETE_STRENGTH = 'INVALID_CONCRETE_STRENGTH';
    case INVALID_STEEL_STRENGTH = 'INVALID_STEEL_STRENGTH';
    case INVALID_REQUIRED_REINFORCEMENT = 'INVALID_REQUIRED_REINFORCEMENT';
    case INVALID_PROVIDED_REINFORCEMENT = 'INVALID_PROVIDED_REINFORCEMENT';
    case INVALID_DEFLECTION_REQUIREMENTS = 'INVALID_DEFLECTION_REQUIREMENTS';
}
