<?php

namespace App\StructuralCalculation\Beams;

enum BeamLongitudinalReinforcementRejectionReason: string
{
    case REINFORCEMENT_NOT_ALLOWED_IN_DESIGN = 'REINFORCEMENT_NOT_ALLOWED_IN_DESIGN';
    case MISSING_TENSION_BAR_COUNT = 'MISSING_TENSION_BAR_COUNT';
    case INVALID_TENSION_BAR_COUNT = 'INVALID_TENSION_BAR_COUNT';
    case MISSING_TENSION_BAR_DIAMETER = 'MISSING_TENSION_BAR_DIAMETER';
    case INVALID_TENSION_BAR_DIAMETER = 'INVALID_TENSION_BAR_DIAMETER';
    case UNSUPPORTED_TENSION_REBAR_LAYERS = 'UNSUPPORTED_TENSION_REBAR_LAYERS';
}
