<?php

namespace App\StructuralCalculation\Beams;

enum BeamConfigurationRejectionReason: string
{
    case INVALID_CONFIGURATION_VALUE = 'INVALID_CONFIGURATION_VALUE';
    case UNSUPPORTED_ELEMENT_TYPE = 'UNSUPPORTED_ELEMENT_TYPE';
    case UNSUPPORTED_MATERIAL_TYPE = 'UNSUPPORTED_MATERIAL_TYPE';
    case UNSUPPORTED_SECTION_TYPE = 'UNSUPPORTED_SECTION_TYPE';
    case UNSUPPORTED_SUPPORT_SYSTEM = 'UNSUPPORTED_SUPPORT_SYSTEM';
    case UNSUPPORTED_LOAD_MODEL = 'UNSUPPORTED_LOAD_MODEL';
    case UNSUPPORTED_DESIGN_SITUATION = 'UNSUPPORTED_DESIGN_SITUATION';
    case UNSUPPORTED_DESIGN_CODE_PROFILE = 'UNSUPPORTED_DESIGN_CODE_PROFILE';
}
