<?php

namespace App\StructuralCalculation\Beams;

enum BeamNeutralAxisRejectionReason: string
{
    case INVALID_REDUCED_DESIGN_MOMENT = 'INVALID_REDUCED_DESIGN_MOMENT';
    case INVALID_EFFECTIVE_DEPTH = 'INVALID_EFFECTIVE_DEPTH';
    case INVALID_STRESS_BLOCK_LAMBDA = 'INVALID_STRESS_BLOCK_LAMBDA';
    case INVALID_STRESS_BLOCK_ETA = 'INVALID_STRESS_BLOCK_ETA';
    case INVALID_NEUTRAL_AXIS_RADICAND = 'INVALID_NEUTRAL_AXIS_RADICAND';
}
