<?php

namespace App\StructuralCalculation\Beams;

enum BeamCrackVerificationRejectionReason: string
{
    case MISSING_RECOMMENDED_STIRRUP = 'MISSING_RECOMMENDED_STIRRUP';
    case UNSUPPORTED_CRACK_WIDTH_EXPOSURE_CLASS = 'UNSUPPORTED_CRACK_WIDTH_EXPOSURE_CLASS';
    case INVALID_SECTION_WIDTH = 'INVALID_SECTION_WIDTH';
    case INVALID_SECTION_HEIGHT = 'INVALID_SECTION_HEIGHT';
    case INVALID_EFFECTIVE_DEPTH = 'INVALID_EFFECTIVE_DEPTH';
    case INVALID_CRACKED_NEUTRAL_AXIS = 'INVALID_CRACKED_NEUTRAL_AXIS';
    case INVALID_TENSION_REINFORCEMENT = 'INVALID_TENSION_REINFORCEMENT';
    case INVALID_BAR_LAYOUT = 'INVALID_BAR_LAYOUT';
    case INVALID_NOMINAL_COVER = 'INVALID_NOMINAL_COVER';
    case INVALID_TRANSVERSE_BAR_DIAMETER = 'INVALID_TRANSVERSE_BAR_DIAMETER';
    case INVALID_STEEL_MODULUS = 'INVALID_STEEL_MODULUS';
    case INVALID_CONCRETE_TENSILE_STRENGTH = 'INVALID_CONCRETE_TENSILE_STRENGTH';
    case INVALID_MODULAR_RATIO = 'INVALID_MODULAR_RATIO';
    case INVALID_STEEL_STRESS = 'INVALID_STEEL_STRESS';
    case INVALID_CRACK_WIDTH_REQUIREMENTS = 'INVALID_CRACK_WIDTH_REQUIREMENTS';
    case INVALID_CRACK_WIDTH_LIMIT = 'INVALID_CRACK_WIDTH_LIMIT';
}
