<?php

namespace App\StructuralCalculation\Beams;

enum BeamMaterialsRejectionReason: string
{
    case MISSING_CONCRETE_CLASS = 'MISSING_CONCRETE_CLASS';
    case INVALID_CONCRETE_CLASS = 'INVALID_CONCRETE_CLASS';
    case UNSUPPORTED_CONCRETE_CLASS = 'UNSUPPORTED_CONCRETE_CLASS';
    case MISSING_STEEL_GRADE = 'MISSING_STEEL_GRADE';
    case INVALID_STEEL_GRADE = 'INVALID_STEEL_GRADE';
    case UNSUPPORTED_STEEL_GRADE = 'UNSUPPORTED_STEEL_GRADE';
    case MISSING_EXPOSURE_CLASSES = 'MISSING_EXPOSURE_CLASSES';
    case INVALID_EXPOSURE_CLASS = 'INVALID_EXPOSURE_CLASS';
    case UNSUPPORTED_EXPOSURE_CLASS = 'UNSUPPORTED_EXPOSURE_CLASS';
    case DUPLICATE_EXPOSURE_CLASS = 'DUPLICATE_EXPOSURE_CLASS';
}
