<?php

namespace App\StructuralCalculation\Beams;

enum BeamFlexuralDomainCheckRejectionReason: string
{
    case INCONSISTENT_EFFECTIVE_DEPTH = 'INCONSISTENT_EFFECTIVE_DEPTH';
    case INVALID_EFFECTIVE_DEPTH = 'INVALID_EFFECTIVE_DEPTH';
    case INVALID_NEUTRAL_AXIS_DEPTH = 'INVALID_NEUTRAL_AXIS_DEPTH';
    case NEUTRAL_AXIS_BEYOND_EFFECTIVE_DEPTH = 'NEUTRAL_AXIS_BEYOND_EFFECTIVE_DEPTH';
    case INVALID_NEUTRAL_AXIS_RATIO = 'INVALID_NEUTRAL_AXIS_RATIO';
    case INCONSISTENT_NEUTRAL_AXIS = 'INCONSISTENT_NEUTRAL_AXIS';
    case INVALID_STEEL_DESIGN_STRENGTH = 'INVALID_STEEL_DESIGN_STRENGTH';
    case INVALID_STEEL_ELASTIC_MODULUS = 'INVALID_STEEL_ELASTIC_MODULUS';
}
