<?php

namespace App\StructuralCalculation\Beams;

enum BeamReducedMomentRejectionReason: string
{
    case INVALID_DESIGN_MOMENT = 'INVALID_DESIGN_MOMENT';
    case INVALID_SECTION_WIDTH = 'INVALID_SECTION_WIDTH';
    case INVALID_EFFECTIVE_DEPTH = 'INVALID_EFFECTIVE_DEPTH';
    case INVALID_CONCRETE_DESIGN_STRENGTH = 'INVALID_CONCRETE_DESIGN_STRENGTH';
    case INVALID_NORMALIZATION_TERM = 'INVALID_NORMALIZATION_TERM';
}
