<?php

namespace App\StructuralCalculation\Beams;

enum BeamPermanentLoadsRejectionReason: string
{
    case MISSING_INCLUDE_SELF_WEIGHT = 'MISSING_INCLUDE_SELF_WEIGHT';
    case INVALID_INCLUDE_SELF_WEIGHT = 'INVALID_INCLUDE_SELF_WEIGHT';
    case MISSING_ADDITIONAL_PERMANENT_LOAD = 'MISSING_ADDITIONAL_PERMANENT_LOAD';
    case INVALID_ADDITIONAL_PERMANENT_LOAD = 'INVALID_ADDITIONAL_PERMANENT_LOAD';
}
