<?php

namespace App\StructuralCalculation\Beams;

enum BeamRequiredTensionReinforcementRejectionReason: string
{
    case INVALID_DESIGN_MOMENT = 'INVALID_DESIGN_MOMENT';
    case INVALID_STEEL_DESIGN_STRENGTH = 'INVALID_STEEL_DESIGN_STRENGTH';
    case INVALID_LEVER_ARM = 'INVALID_LEVER_ARM';
    case INVALID_STEEL_LEVER_ARM_PRODUCT = 'INVALID_STEEL_LEVER_ARM_PRODUCT';
    case INVALID_REQUIRED_REINFORCEMENT_AREA = 'INVALID_REQUIRED_REINFORCEMENT_AREA';
}
