<?php

namespace App\StructuralCalculation\Beams;

enum BeamLeverArmRejectionReason: string
{
    case INVALID_EFFECTIVE_DEPTH = 'INVALID_EFFECTIVE_DEPTH';
    case INCONSISTENT_EFFECTIVE_DEPTH = 'INCONSISTENT_EFFECTIVE_DEPTH';
    case INVALID_NEUTRAL_AXIS_DEPTH = 'INVALID_NEUTRAL_AXIS_DEPTH';
    case NEUTRAL_AXIS_BEYOND_EFFECTIVE_DEPTH = 'NEUTRAL_AXIS_BEYOND_EFFECTIVE_DEPTH';
    case INVALID_STRESS_BLOCK_LAMBDA = 'INVALID_STRESS_BLOCK_LAMBDA';
    case NON_POSITIVE_LEVER_ARM = 'NON_POSITIVE_LEVER_ARM';
}
