<?php

namespace App\StructuralCalculation\Beams;

enum BeamEffectiveDepthRejectionReason: string
{
    case INVALID_OVERALL_DEPTH = 'INVALID_OVERALL_DEPTH';
    case INVALID_NOMINAL_COVER = 'INVALID_NOMINAL_COVER';
    case INVALID_NOMINAL_COVER_UNIT = 'INVALID_NOMINAL_COVER_UNIT';
    case INVALID_TRANSVERSE_REINFORCEMENT_DIAMETER = 'INVALID_TRANSVERSE_REINFORCEMENT_DIAMETER';
    case INVALID_DESIGN_TENSION_BAR_DIAMETER = 'INVALID_DESIGN_TENSION_BAR_DIAMETER';
    case MISSING_VERIFICATION_REINFORCEMENT = 'MISSING_VERIFICATION_REINFORCEMENT';
    case INVALID_VERIFICATION_TENSION_BAR_DIAMETER = 'INVALID_VERIFICATION_TENSION_BAR_DIAMETER';
    case UNSUPPORTED_TENSION_REINFORCEMENT_LAYERS = 'UNSUPPORTED_TENSION_REINFORCEMENT_LAYERS';
    case NON_POSITIVE_EFFECTIVE_DEPTH = 'NON_POSITIVE_EFFECTIVE_DEPTH';
}
