<?php

namespace App\StructuralCalculation\Beams;

enum BeamUltimateCombinationRejectionReason: string
{
    case INVALID_TOTAL_PERMANENT_LOAD = 'INVALID_TOTAL_PERMANENT_LOAD';
    case INVALID_VARIABLE_CHARACTERISTIC_LOAD = 'INVALID_VARIABLE_CHARACTERISTIC_LOAD';
    case INVALID_UNFAVOURABLE_PERMANENT_PARTIAL_FACTOR = 'INVALID_UNFAVOURABLE_PERMANENT_PARTIAL_FACTOR';
    case INVALID_VARIABLE_PARTIAL_FACTOR = 'INVALID_VARIABLE_PARTIAL_FACTOR';
}
