<?php

namespace App\StructuralCalculation\Beams;

enum BeamServiceabilityCombinationRejectionReason: string
{
    case INVALID_TOTAL_PERMANENT_LOAD = 'INVALID_TOTAL_PERMANENT_LOAD';
    case INVALID_VARIABLE_CHARACTERISTIC_LOAD = 'INVALID_VARIABLE_CHARACTERISTIC_LOAD';
    case MISSING_VARIABLE_ACTION_FACTORS = 'MISSING_VARIABLE_ACTION_FACTORS';
    case INVALID_FREQUENT_VARIABLE_FACTOR = 'INVALID_FREQUENT_VARIABLE_FACTOR';
    case INVALID_QUASI_PERMANENT_VARIABLE_FACTOR = 'INVALID_QUASI_PERMANENT_VARIABLE_FACTOR';
}
