<?php

namespace App\StructuralCalculation\Beams;

enum BeamStirrupProposalRejectionReason: string
{
    case INSUFFICIENT_REINFORCEMENT_PER_LENGTH = 'INSUFFICIENT_REINFORCEMENT_PER_LENGTH';
    case LONGITUDINAL_SPACING_EXCEEDED = 'LONGITUDINAL_SPACING_EXCEEDED';
    case TRANSVERSE_LEG_SPACING_EXCEEDED = 'TRANSVERSE_LEG_SPACING_EXCEEDED';
    case MAXIMUM_SHEAR_RESISTANCE_EXCEEDED = 'MAXIMUM_SHEAR_RESISTANCE_EXCEEDED';
    case SHEAR_RESISTANCE_INSUFFICIENT = 'SHEAR_RESISTANCE_INSUFFICIENT';
}
