<?php

namespace App\StructuralCalculation\Beams;

enum BeamVariableLoadRejectionReason: string
{
    case MISSING_VARIABLE_ACTION_CATEGORY = 'MISSING_VARIABLE_ACTION_CATEGORY';
    case INVALID_VARIABLE_ACTION_CATEGORY = 'INVALID_VARIABLE_ACTION_CATEGORY';
    case UNSUPPORTED_VARIABLE_ACTION_CATEGORY = 'UNSUPPORTED_VARIABLE_ACTION_CATEGORY';
    case MISSING_CHARACTERISTIC_VARIABLE_LOAD = 'MISSING_CHARACTERISTIC_VARIABLE_LOAD';
    case INVALID_CHARACTERISTIC_VARIABLE_LOAD = 'INVALID_CHARACTERISTIC_VARIABLE_LOAD';
}
