<?php

namespace App\StructuralCalculation\Beams;

enum BeamServiceStressVerificationRejectionReason: string
{
    case UNSUPPORTED_COMPRESSED_REINFORCEMENT_SLS = 'UNSUPPORTED_COMPRESSED_REINFORCEMENT_SLS';
    case INVALID_SECTION_WIDTH = 'INVALID_SECTION_WIDTH';
    case INVALID_SECTION_HEIGHT = 'INVALID_SECTION_HEIGHT';
    case INVALID_EFFECTIVE_DEPTH = 'INVALID_EFFECTIVE_DEPTH';
    case INVALID_TENSION_REINFORCEMENT_AREA = 'INVALID_TENSION_REINFORCEMENT_AREA';
    case INVALID_CONCRETE_MODULUS = 'INVALID_CONCRETE_MODULUS';
    case INVALID_STEEL_MODULUS = 'INVALID_STEEL_MODULUS';
    case INVALID_CONCRETE_STRENGTH = 'INVALID_CONCRETE_STRENGTH';
    case INVALID_STEEL_STRENGTH = 'INVALID_STEEL_STRENGTH';
    case INVALID_SERVICE_MOMENT = 'INVALID_SERVICE_MOMENT';
    case INVALID_STRESS_LIMIT_FACTOR = 'INVALID_STRESS_LIMIT_FACTOR';
    case INVALID_CRACKED_NEUTRAL_AXIS = 'INVALID_CRACKED_NEUTRAL_AXIS';
    case INVALID_CRACKED_SECOND_MOMENT_OF_AREA = 'INVALID_CRACKED_SECOND_MOMENT_OF_AREA';
}
