<?php

namespace App\StructuralCalculation\Beams;

enum BeamMaximumShearResistanceRejectionReason: string
{
    case INVALID_DESIGN_SHEAR_FORCE = 'INVALID_DESIGN_SHEAR_FORCE';
    case INVALID_WEB_WIDTH = 'INVALID_WEB_WIDTH';
    case INVALID_LEVER_ARM = 'INVALID_LEVER_ARM';
    case INVALID_CONCRETE_CHARACTERISTIC_STRENGTH = 'INVALID_CONCRETE_CHARACTERISTIC_STRENGTH';
    case INVALID_CONCRETE_DESIGN_STRENGTH = 'INVALID_CONCRETE_DESIGN_STRENGTH';
    case INVALID_COT_THETA = 'INVALID_COT_THETA';
    case COT_THETA_OUTSIDE_PROFILE_RANGE = 'COT_THETA_OUTSIDE_PROFILE_RANGE';
    case INVALID_REDUCTION_COEFFICIENT = 'INVALID_REDUCTION_COEFFICIENT';
    case INVALID_REDUCTION_REFERENCE_STRENGTH = 'INVALID_REDUCTION_REFERENCE_STRENGTH';
    case INVALID_ALPHA_CW = 'INVALID_ALPHA_CW';
    case INVALID_MAXIMUM_SHEAR_RESISTANCE = 'INVALID_MAXIMUM_SHEAR_RESISTANCE';
}
