<?php

namespace App\StructuralCalculation\Beams;

enum BeamAnalysisRejectionReason: string
{
    case CALCULATION_METHOD_NOT_SUPPORTED = 'CALCULATION_METHOD_NOT_SUPPORTED';
    case CANTILEVER_FIXED_END_SHEAR_VERIFICATION_NOT_SUPPORTED = 'CANTILEVER_FIXED_END_SHEAR_VERIFICATION_NOT_SUPPORTED';
}
