<?php

namespace App\StructuralCalculation\Beams;

enum BeamFlexuralDesignStrengthsRejectionReason: string
{
    case INVALID_CHARACTERISTIC_CONCRETE_STRENGTH = 'INVALID_CHARACTERISTIC_CONCRETE_STRENGTH';
    case INVALID_CHARACTERISTIC_STEEL_STRENGTH = 'INVALID_CHARACTERISTIC_STEEL_STRENGTH';
    case INVALID_CONCRETE_PARTIAL_FACTOR = 'INVALID_CONCRETE_PARTIAL_FACTOR';
    case INVALID_STEEL_PARTIAL_FACTOR = 'INVALID_STEEL_PARTIAL_FACTOR';
    case INVALID_CONCRETE_ALPHA_COEFFICIENT = 'INVALID_CONCRETE_ALPHA_COEFFICIENT';
    case INVALID_DESIGN_CONCRETE_STRENGTH = 'INVALID_DESIGN_CONCRETE_STRENGTH';
    case INVALID_DESIGN_STEEL_STRENGTH = 'INVALID_DESIGN_STEEL_STRENGTH';
}
