<?php

namespace App\StructuralCalculation\Beams;

enum BeamCalculationInputRejectionReason: string
{
    case MISSING_CONFIGURATION = 'MISSING_CONFIGURATION';
    case INVALID_CONFIGURATION_STRUCTURE = 'INVALID_CONFIGURATION_STRUCTURE';
    case MISSING_GEOMETRY = 'MISSING_GEOMETRY';
    case INVALID_GEOMETRY_STRUCTURE = 'INVALID_GEOMETRY_STRUCTURE';
    case INVALID_GEOMETRY_UNIT = 'INVALID_GEOMETRY_UNIT';
    case MISSING_MATERIALS = 'MISSING_MATERIALS';
    case INVALID_MATERIALS_STRUCTURE = 'INVALID_MATERIALS_STRUCTURE';
    case MISSING_LOADS = 'MISSING_LOADS';
    case INVALID_LOADS_STRUCTURE = 'INVALID_LOADS_STRUCTURE';
    case INVALID_PERMANENT_LOAD_UNIT = 'INVALID_PERMANENT_LOAD_UNIT';
    case INVALID_VARIABLE_LOAD_UNIT = 'INVALID_VARIABLE_LOAD_UNIT';
    case MISSING_REINFORCEMENT = 'MISSING_REINFORCEMENT';
    case INVALID_REINFORCEMENT_STRUCTURE = 'INVALID_REINFORCEMENT_STRUCTURE';
    case INVALID_REINFORCEMENT_DIAMETER_UNIT = 'INVALID_REINFORCEMENT_DIAMETER_UNIT';
    case UNEXPECTED_PAYLOAD_PROPERTY = 'UNEXPECTED_PAYLOAD_PROPERTY';
}
