<?php

namespace App\StructuralCalculation\Beams;

enum BeamShearForceRejectionReason: string
{
    case UNSUPPORTED_SUPPORT_SYSTEM = 'UNSUPPORTED_SUPPORT_SYSTEM';
    case UNSUPPORTED_LOAD_MODEL = 'UNSUPPORTED_LOAD_MODEL';
    case INVALID_EFFECTIVE_SPAN = 'INVALID_EFFECTIVE_SPAN';
    case INVALID_ULTIMATE_LINE_LOAD = 'INVALID_ULTIMATE_LINE_LOAD';
    case INVALID_CHARACTERISTIC_SERVICEABILITY_LINE_LOAD = 'INVALID_CHARACTERISTIC_SERVICEABILITY_LINE_LOAD';
    case INVALID_FREQUENT_SERVICEABILITY_LINE_LOAD = 'INVALID_FREQUENT_SERVICEABILITY_LINE_LOAD';
    case INVALID_QUASI_PERMANENT_SERVICEABILITY_LINE_LOAD = 'INVALID_QUASI_PERMANENT_SERVICEABILITY_LINE_LOAD';
}
