<?php

namespace App\StructuralCalculation\Beams;

enum BeamMinimumTensionReinforcementRejectionReason: string
{
    case INVALID_MEAN_TENSILE_CONCRETE_STRENGTH = 'INVALID_MEAN_TENSILE_CONCRETE_STRENGTH';
    case INVALID_CHARACTERISTIC_STEEL_STRENGTH = 'INVALID_CHARACTERISTIC_STEEL_STRENGTH';
    case INVALID_TENSION_ZONE_MEAN_WIDTH = 'INVALID_TENSION_ZONE_MEAN_WIDTH';
    case INVALID_EFFECTIVE_DEPTH = 'INVALID_EFFECTIVE_DEPTH';
    case INVALID_STRENGTH_COEFFICIENT = 'INVALID_STRENGTH_COEFFICIENT';
    case INVALID_MINIMUM_REINFORCEMENT_RATIO = 'INVALID_MINIMUM_REINFORCEMENT_RATIO';
    case INVALID_TENSION_ZONE_AREA = 'INVALID_TENSION_ZONE_AREA';
    case INVALID_MINIMUM_REINFORCEMENT_AREA = 'INVALID_MINIMUM_REINFORCEMENT_AREA';
}
