<?php

namespace App\StructuralCalculation\Beams;

enum BeamConcreteShearResistanceRejectionReason: string
{
    case INVALID_DESIGN_SHEAR_FORCE = 'INVALID_DESIGN_SHEAR_FORCE';
    case UNSUPPORTED_SECTION_TYPE = 'UNSUPPORTED_SECTION_TYPE';
    case INVALID_WEB_WIDTH = 'INVALID_WEB_WIDTH';
    case INVALID_CONCRETE_AREA = 'INVALID_CONCRETE_AREA';
    case INVALID_EFFECTIVE_DEPTH = 'INVALID_EFFECTIVE_DEPTH';
    case INVALID_CONCRETE_STRENGTH = 'INVALID_CONCRETE_STRENGTH';
    case INVALID_CONCRETE_DESIGN_STRENGTH = 'INVALID_CONCRETE_DESIGN_STRENGTH';
    case INVALID_LONGITUDINAL_REINFORCEMENT_AREA = 'INVALID_LONGITUDINAL_REINFORCEMENT_AREA';
    case UNSUPPORTED_NORMAL_FORCE = 'UNSUPPORTED_NORMAL_FORCE';
    case INVALID_CONCRETE_SHEAR_RESISTANCE_COEFFICIENT = 'INVALID_CONCRETE_SHEAR_RESISTANCE_COEFFICIENT';
    case INVALID_COMPRESSION_STRESS_COEFFICIENT = 'INVALID_COMPRESSION_STRESS_COEFFICIENT';
    case INVALID_MINIMUM_SHEAR_STRESS_COEFFICIENT = 'INVALID_MINIMUM_SHEAR_STRESS_COEFFICIENT';
    case INVALID_SIZE_EFFECT_REFERENCE_DEPTH = 'INVALID_SIZE_EFFECT_REFERENCE_DEPTH';
    case INVALID_MAXIMUM_SIZE_EFFECT_FACTOR = 'INVALID_MAXIMUM_SIZE_EFFECT_FACTOR';
    case INVALID_MAXIMUM_LONGITUDINAL_REINFORCEMENT_RATIO = 'INVALID_MAXIMUM_LONGITUDINAL_REINFORCEMENT_RATIO';
}
